apiVersion: v1
kind: Service
metadata:
  name: api-hacka-service
spec:
  selector:
    app: api-hacka
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31000
  type: LoadBalancer
