apiVersion: v1
kind: Secret
metadata:
  name: api-hacka-secrets
type: Opaque
data:
  MONGO_URL: bW9uZ29kYjovL3VzZXJib2xhZG86cGFzc3dvcmRib2xhZGFAZGItYXBpLWhhY2thLXNlcnZpY2U6MjcwMTc=
  PORT: MzAwMA==
  EMAIL_SERVICE_USER: cGVyLmdhYnJpZWxhcmFuZGFAZ21haWwuY29t
  EMAIL_SERVICE_PASSWORD: d3d4ZGtqeWV2dnFjanpzbw==
